### ISSUE TITLE
Add docker and docker-compose support for scripts dev generator

### ISSUE THREAD

**Issue by rqc** [eedevops/generator-hubot-enterprise#1]
Following the feedback from @JonathanRosado  and @gmatoshp on their experience setting up the hubot script (agm) dev environment and the workflow that they have to use, we would like to recommend that we explore the following approach: 

- we create a dockerized version of hubot with the *enterprise* integration
- in the `yo` generator for scripts, we could generate a `docker-compose.yml` that uses the previosuly mentioned docker image, and *mounts* the appropriate local scripts that you are developing within the `/scripts` directory in the container. So, to run / play with your hubot script / integration during develpment, you just have to perform `docker-compose up`.

@edagan @eitanshp @mosheBelostotsky @eitzhaki What do you think?

**Comment by eitzhaki** [comment]
The fastest way existing is to use the following shell script that updates the files that were changed and bring up hubot. any other solution that will bring/build a docker image will take more time.

1.	you can work on a folder on windows machine
2.	Starting vmware linux server
3.	Mounting the directory to linux as shared one
4.	Creating hubot instance on the linux machine (e.g: /opt/hubot_dev)
5.	Running the following scrtip from the hubot_dev folder in linux machine: (rename the attached file from .txt to .sh
[dev_and_run.txt](https://github.com/eedevops/generator-hubot-enterprise/files/388284/dev_and_run.txt)
)

**Comment by rqc** [comment]
@eitzhaki thanks for your feedback! Regarding the steps above, I think that it is a good approach. In fact, this would be even easier to do in windows if we use [docker toolbox](https://www.docker.com/products/docker-toolbox). The value added with using `docker` in general is that you may use the same workflow if you develop in a linux environment, either in our machines or elsewhere. And furthermore, a developer would not have to resort to using `rsync` or setup explicit `symlinks`. 

I will work with @JonathanRosado and @gmatoshp to do a spike on this and see if it works out.

**Comment by eitzhaki** [comment]
show me the benefit :)

**Comment by eitanshp** [comment]
I remind you guys that people are developing/using our scripts from Windows as well - take that under advisement. Not sure why you need `rsync` @rqc - once you mount a shared volume from Windows to a VMWare VM, it' automatically updated at all times.

**Comment by rqc** [comment]
@eitanshp I mentioned `rsync` because it is being used in the [script](https://github.com/eedevops/generator-hubot-enterprise/files/388284/dev_and_run.txt) that @eitzhaki attached above. I didn't write that. Furthermore, I concurred that using VMWare in that way does the job for Windows users, but not for us cool Linux users :wink: That's where docker really shines.

**Comment by eitanshp** [comment]
Let's take it offline - I see no need to rsync *anything* once you use a mounted volume. You have all the files synced by default so regardless of where you work (Windows to Linux VM, Linux to Docker container) the concept remains the same - mounted volume.

**Comment by rqc** [comment]
Referencing https://github.com/eedevops/generator-hubot-enterprise/pull/7

**Comment by rqc** [comment]
@JonathanRosado please consider what @mosheBelostotsky mentioned today. That when we use the `yo hubot-enterprise` generator to generate an *instance* of `hubot` and NOT the *script* structure, then a similar `docker-compose.yml` could be generated. However, *we should think about* weather this is a priority use case...

**Comment by JonathanRosado** [comment]
@rqc Will do. As this was not part of the original plan, I'll need an additional user story allocated for this task.

**Comment by rqc** [comment]
@JonathanRosado ok, create the story, put it in the backlog but I don't think this is priority right now. Make sure you document all images, and how to use the `docker-compose.yml` in the wiki.

**Comment by rqc** [comment]
Fixed in https://github.com/eedevops/generator-hubot-enterprise/pull/7 @JonathanRosado thanks for the pull request.
